version: "3.8"
services:
  docs_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: codeDocs
    ports:
      - "9000:3000"
    volumes:
      - ./:/app
      - /app/node_modules/
