version: "3.8"
services:
  docs_server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: codeDocs
    ports:
      - "9000:3000"
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs
      - ./blog:/app/blog
      - /app/node_modules/
