/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "git",
    {
      type: "category",
      label: "Python",
      items: [
        "python/intro",
        "python/flask",
        "python/databases",
        "python/pyqt6",
        "python/pandas",
        "python/selenium",
        "python/other",
      ],
    },
    {
      type: "category",
      label: "JavaScript",
      items: [
        "javascript/intro",
        "javascript/node",
        "javascript/express",
        "javascript/react",
        "javascript/next",
        "javascript/databases",
        "javascript/other",
      ],
    },
    "css",
    "docker",
    "sql",
    "bash",
    "cli",
  ],
};

module.exports = sidebars;
